#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GooglePlayServicesTest.Resource", IsApplication=true)]

namespace GooglePlayServicesTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int layers_array = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_google_signin_btn_text_dark = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_light = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_tint = 2131099658;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int badge_nsw = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int badge_qld = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int badge_sa = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int badge_victoria = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int badge_wa = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_full_open_on_phone = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_disabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_normal_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_normal_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_normal_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int custom_info_bubble = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int googleg_disabled_color_18 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int googleg_standard_color_18 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int newark_nj_1922 = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int adjust_height = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int adjust_width = 2131230726;
			
			// aapt resource value: 0x7f080031
			public const int alphaSeekBar = 2131230769;
			
			// aapt resource value: 0x7f080010
			public const int animate = 2131230736;
			
			// aapt resource value: 0x7f08000a
			public const int auto = 2131230730;
			
			// aapt resource value: 0x7f08001a
			public const int badge = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int bondi = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int button_blutooth = 2131230733;
			
			// aapt resource value: 0x7f08001f
			public const int camera_text = 2131230751;
			
			// aapt resource value: 0x7f080034
			public const int compass_toggle = 2131230772;
			
			// aapt resource value: 0x7f080028
			public const int custom_info_contents = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int custom_info_window = 2131230761;
			
			// aapt resource value: 0x7f080026
			public const int custom_info_window_options = 2131230758;
			
			// aapt resource value: 0x7f08000b
			public const int dark = 2131230731;
			
			// aapt resource value: 0x7f080027
			public const int default_info_window = 2131230759;
			
			// aapt resource value: 0x7f080020
			public const int description = 2131230752;
			
			// aapt resource value: 0x7f080030
			public const int hueSeekBar = 2131230768;
			
			// aapt resource value: 0x7f080000
			public const int hybrid = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int icon_only = 2131230727;
			
			// aapt resource value: 0x7f080022
			public const int layers_spinner = 2131230754;
			
			// aapt resource value: 0x7f08000c
			public const int light = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int location_text = 2131230734;
			
			// aapt resource value: 0x7f080019
			public const int map = 2131230745;
			
			// aapt resource value: 0x7f08002c
			public const int map1 = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int map2 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int map3 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int map4 = 2131230767;
			
			// aapt resource value: 0x7f08002a
			public const int map_container = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int map_container2 = 2131230763;
			
			// aapt resource value: 0x7f080024
			public const int my_location = 2131230756;
			
			// aapt resource value: 0x7f080035
			public const int mylocationbutton_toggle = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int mylocationlayer_toggle = 2131230774;
			
			// aapt resource value: 0x7f080001
			public const int none = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f08001d
			public const int root = 2131230749;
			
			// aapt resource value: 0x7f08003a
			public const int rotate_toggle = 2131230778;
			
			// aapt resource value: 0x7f080003
			public const int satellite = 2131230723;
			
			// aapt resource value: 0x7f080013
			public const int scroll_down = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int scroll_left = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int scroll_right = 2131230740;
			
			// aapt resource value: 0x7f080037
			public const int scroll_toggle = 2131230775;
			
			// aapt resource value: 0x7f080012
			public const int scroll_up = 2131230738;
			
			// aapt resource value: 0x7f08001c
			public const int snippet = 2131230748;
			
			// aapt resource value: 0x7f080008
			public const int standard = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int stop_animation = 2131230735;
			
			// aapt resource value: 0x7f080017
			public const int sydney = 2131230743;
			
			// aapt resource value: 0x7f08001e
			public const int tap_text = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int terrain = 2131230724;
			
			// aapt resource value: 0x7f080039
			public const int tilt_toggle = 2131230777;
			
			// aapt resource value: 0x7f08001b
			public const int title = 2131230747;
			
			// aapt resource value: 0x7f080025
			public const int top_text = 2131230757;
			
			// aapt resource value: 0x7f080023
			public const int traffic = 2131230755;
			
			// aapt resource value: 0x7f080021
			public const int transparencySeekBar = 2131230753;
			
			// aapt resource value: 0x7f080009
			public const int wide = 2131230729;
			
			// aapt resource value: 0x7f080032
			public const int widthSeekBar = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int zoom_buttons_toggle = 2131230771;
			
			// aapt resource value: 0x7f080038
			public const int zoom_gestures_toggle = 2131230776;
			
			// aapt resource value: 0x7f080015
			public const int zoom_in = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int zoom_out = 2131230742;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int basic_demo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int basic_demo_blutooth = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int camera_demo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int custom_info_contents = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int custom_info_window = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int empty = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int events_demo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int feature = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ground_overlay_demo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int layers_demo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int marker_demo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int multimap_demo = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int options_demo = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int polygon_demo = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int polyline_demo = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int raw_mapview_demo = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ui_settings_demo = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050011
			public const int alpha = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int animate = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int basic_description = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int basic_map = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int camera_demo = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int camera_description = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int clear_map = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int compass = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int custom_info_contents = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int custom_info_window = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int default_info_window = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int demo_title = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int down_arrow = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int drag_melbourne = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int events_demo = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int events_description = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int fill_alpha = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int fill_hue = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int go_to_bondi = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int go_to_sydney = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int groundoverlay_demo = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int groundoverlay_description = 2131034151;
			
			// aapt resource value: 0x7f05001f
			public const int hue = 2131034143;
			
			// aapt resource value: 0x7f050028
			public const int hybrid = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int layers_demo = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int layers_description = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int left_arrow = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int locationsource_demo = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int locationsource_description = 2131034157;
			
			// aapt resource value: 0x7f050032
			public const int map_not_ready = 2131034162;
			
			// aapt resource value: 0x7f05002e
			public const int marker_demo = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int marker_description = 2131034159;
			
			// aapt resource value: 0x7f050033
			public const int move_the_camera = 2131034163;
			
			// aapt resource value: 0x7f050030
			public const int multi_map_demo = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int multi_map_description = 2131034161;
			
			// aapt resource value: 0x7f050034
			public const int my_location = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int mylocation_button = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int mylocation_layer = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int no_demos = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int normal = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int options_demo = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int options_description = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int polygon_demo = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int polygon_description = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int polyline_demo = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int polyline_description = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int programmatic_demo = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int programmatic_description = 2131034176;
			
			// aapt resource value: 0x7f050042
			public const int properties_sydney_polygon = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int properties_sydney_polyline = 2131034177;
			
			// aapt resource value: 0x7f050044
			public const int raw_mapview_demo = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int raw_mapview_description = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int reset_map = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int retain_map = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int retain_map_description = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int right_arrow = 2131034185;
			
			// aapt resource value: 0x7f050043
			public const int rotate = 2131034179;
			
			// aapt resource value: 0x7f05004a
			public const int satellite = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int scroll = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int stop_animation = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int stroke_width = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int tap_instructions = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int terrain = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int tile_overlay_demo = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int tile_overlay_description = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int tilt = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int traffic = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int transparency = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int uisettings_demo = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int uisettings_description = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int up_arrow = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int width = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int zoom_buttons = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int zoom_gestures = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int zoom_in = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int zoom_out = 2131034204;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
